path: C:\Users\othma\PycharmProjects\Semantic Segmentation using YOLOV8\data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes (80 COCO classes)
names:
  0: ducks